stages:
  - security-scan
  - build

variables:
  DOCKER_USERNAME: "sarra539"
  BACKEND_IMAGE: "sarra539/autoflow-repo:Version1"
  FRONTEND_IMAGE: "sarra539/autoflow-front:version1"
  SECURE_BACKEND_IMAGE: "sarra539/autoflow-repo:secure-latest"
  USE_SECURE_IMAGE: "true"

default:
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build-backend:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - cd backend-autoflow
    - docker build --no-cache --pull -f Dockerfile.secure.hybrid -t "$SECURE_BACKEND_IMAGE" .
    - docker push "$SECURE_BACKEND_IMAGE"
  retry:
    max: 2
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build-frontend:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - cd frontend-autoflow
    - docker build --no-cache -t "$FRONTEND_IMAGE" .
    - docker push "$FRONTEND_IMAGE"
  retry:
    max: 2
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'