stages:
  - build
  - deploy

variables:
  DOCKER_USERNAME: "sarra539"

# Build Backend Image
build-backend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - cd backend-autoflow
    - docker build -t $DOCKER_USERNAME/autoflow-repo:VerifUpdate .
    - docker push $DOCKER_USERNAME/autoflow-repo:VerifUpdate
  only:
    - main

# Build Frontend Image
build-frontend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - cd frontend-autoflow
    - docker build -t $DOCKER_USERNAME/autoflow-front:VersionTestKuber9 .
    - docker push $DOCKER_USERNAME/autoflow-front:VersionTestKuber9
  only:
    - main

# Deploy to Kubernetes
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - echo "$KUBE_CONFIG" | base64 -d > kubeconfig
    - export KUBECONFIG=kubeconfig
  script:
    - kubectl version --client
    - kubectl get pods
  environment:
    name: production
    url: http://192.168.111.201:31560
  only:
    - main
  when: manual
