apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: autoflow
  labels:
    app: autoflow-backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoflow-backend
  template:
    metadata:
      labels:
        app: autoflow-backend
        version: v1
    spec:
      containers:
        - name: backend
          image: sarra539/autoflow-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
            - containerPort: 5010
              name: websocket
              protocol: TCP
            - containerPort: 5001
              name: flask-api
              protocol: TCP
            - containerPort: 5003
              name: ai-agents
              protocol: TCP
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: autoflow-config
                  key: NODE_ENV
            - name: BACKUP_DIR
              valueFrom:
                configMapKeyRef:
                  name: autoflow-config
                  key: BACKUP_DIR
            - name: PYTHONPATH
              valueFrom:
                configMapKeyRef:
                  name: autoflow-config
                  key: PYTHONPATH
            - name: FLASK_API_URL
              valueFrom:
                configMapKeyRef:
                  name: autoflow-config
                  key: FLASK_API_URL
            - name: GENERATED_PLAYBOOKS_DIR
              valueFrom:
                configMapKeyRef:
                  name: autoflow-config
                  key: GENERATED_PLAYBOOKS_DIR
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: backup-storage
              mountPath: /app/backups
            - name: logs-storage
              mountPath: /app/logs
            - name: generated-playbooks
              mountPath: /app/generated_playbooks
          startupProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "kill $(cat /app/logs/*.pid) 2>/dev/null || true"]
      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: backup-pvc
        - name: logs-storage
          persistentVolumeClaim:
            claimName: logs-pvc
        - name: generated-playbooks
          emptyDir: {}
      restartPolicy: Always 