apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  labels:
    app: ollama
    component: ai-inference
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""  # Uses default storage class
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-models-pv
  labels:
    app: ollama
    component: ai-inference
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/ollama-models
    type: DirectoryOrCreate 