apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoflow-sa
  namespace: autoflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autoflow-role
  namespace: autoflow
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autoflow-rolebinding
  namespace: autoflow
subjects:
  - kind: ServiceAccount
    name: autoflow-sa
    namespace: autoflow
roleRef:
  kind: Role
  name: autoflow-role
  apiGroup: rbac.authorization.k8s.io 