apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sarra539/autoflow-repo:VerifUpdate
          imagePullPolicy: Always
          ports:
            - containerPort: 5000  # HTTP API
            - containerPort: 5010  # WebSocket
            - containerPort: 5001  # Flask API
            - containerPort: 5003  # AI Agents API
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-url
            - name: NODE_ENV
              value: "production"
            - name: BACKUP_DIR
              value: "/app/backups"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: PYTHONPATH
              value: "/app"
            - name: FLASK_API_URL
              value: "http://localhost:5001"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: backup-storage
              mountPath: /app/backups
            - name: logs-storage
              mountPath: /app/logs
      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: backup-pvc
        - name: logs-storage
          emptyDir: {}
      dnsPolicy: Default
      dnsConfig:
        nameservers:
          - 8.8.8.8
