- name: Create VLAN 50 - Depart50Vlan
  hosts: all
  gather_facts: false
  vars:
    ansible_network_os: ios
    ansible_connection: network_cli
    vlan_id: 50
    vlan_name: Depart50Vlan
    interfaces: []
  tasks:
  - name: Ensure VLAN 50 exists (old-style NM-16ESW)
    ios_command:
      commands:
      - vlan database
      - vlan 50 name Depart50Vlan
      - exit
